### ISSUE TITLE
Unable to use client

### ISSUE THREAD

**Issue by digerata** [ably/ably-ruby-rest#21]
Hello,

New customer, trying to integrate this into a Rails app. I'm hitting the following issue in the basic example in the rails console:

```ruby
2.6.6 :003 > client = Ably::Rest.new(key: 'redacted')
2.6.6 :004 > channel = client.channel('test')
2.6.6 :005 > channel.publish('myEvent', 'Hello!')
ETHON: Libcurl initialized
objc[62707]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[62707]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```
It hard crashes.

I'm on Mac OS 12.2.1 on an M1 Max

Using ably-rest 1.1.8.

Any ideas?

**Comment by owenpearson** [comment]
Hi @digerata, I've had a look in to this and it appears that this is actually a rails issue (rails/rails#38560) which specifically affects M1 Max users. It looks like users in that thread are reporting `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` or `export DISABLE_SPRING=true` as potential workarounds until this issue is resolved by rails.
